## H2 setup - In memory
datasource:
  default: ${APP_ENV}
  development:
    username: sa
    password: sa
    url: "jdbc:h2:./database"
  production:
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    url: ${JDBC_DATABASE_URL}

ebean:
  ddl:
    generate: true
    run: true
    seedSql: seed.sql
    # migration:
    #   run: true